productos = [
    {
        "nombre": "Maruti Suzuki Ertiga ZXI, 2016, Petrol",
        "precio": "₹ 7,36,000",
        "descripcion": "2016 - 68,524 km",
        "localizacion": "VILE PARLE EAST, MUMBAI",
        "imagen": "Sin información",
    },
    {
        "nombre": "5 Door wardrobes with 4 years warranty and COD available",
        "precio": "₹ 13,999",
        "descripcion": "Sin información",
        "localizacion": "ELECTRONIC CITY, BENGALURU",
        "imagen": "Sin información",
    },
    {
        "nombre": "Get iPhone 13 Refurbished at genuine price in your budget",
        "precio": "₹ 18,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "Sin información",
    },
    {
        "nombre": "IPHONE 12PRO(256GB VARIENT URGENT SELLING",
        "precio": "₹ 19,200",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "Sin información",
    },
    {
        "nombre": "Maruti Suzuki Baleno 2018 July Model 2 nd",
        "precio": "₹ 5,75,000",
        "descripcion": "2018 - 60,000 km",
        "localizacion": "SAMUDRAPUR MIDC, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/vcujvrydtjmk-IN/image;s=272x0",
    },
    {
        "nombre": "Maruti Suzuki Alto 800 2005 Petrol 86785 Km Driven",
        "precio": "₹ 34,000",
        "descripcion": "2005 - 86,785 km",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/8subwv0mrnrb2-IN/image;s=272x0",
    },
    {
        "nombre": "We have new latest collection avt 2 online order book",
        "precio": "₹ 2,000",
        "descripcion": "1 Bds - 1 Ba - 60 ft2",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/4t5gzmm44b692-IN/image;s=272x0",
    },
    {
        "nombre": "Cod available",
        "precio": "₹ 1,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/8y9rmc6k6d3o1-IN/image;s=272x0",
    },
    {
        "nombre": "We have new latest collection ultra sim watches online order book",
        "precio": "₹ 2,000",
        "descripcion": "1 Bds - 1 Ba - 50 ft2",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/htt349x4zk8j3-IN/image;s=272x0",
    },
    {
        "nombre": "STYLISH MEN WATCH BRANDED (COD)",
        "precio": "₹ 699",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/wvjplurvarrd-IN/image;s=272x0",
    },
    {
        "nombre": "We have new latest collection ultra sim watches online order book",
        "precio": "₹ 2,000",
        "descripcion": "1 Bds - 1 Ba - 30 ft2",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/kg1gmr0vsitu-IN/image;s=272x0",
    },
    {
        "nombre": "Smart Watch Men",
        "precio": "₹ 550",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/9vth7b0dvb94-IN/image;s=272x0",
    },
    {
        "nombre": "2200 mh battery available 150kg weight present",
        "precio": "₹ 6,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/irpsajba247o-IN/image;s=272x0",
    },
    {
        "nombre": "Smart Watches for Men",
        "precio": "₹ 550",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/wt7v394wtjfj-IN/image;s=272x0",
    },
    {
        "nombre": "RD5 projector 3D 4K wifi smart youtube live tv usb hdmi 145 inch size",
        "precio": "₹ 3,500",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/4cf3xiihltsk-IN/image;s=272x0",
    },
    {
        "nombre": "Track suit",
        "precio": "₹ 799",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/yet5lsw2wqje2-IN/image;s=272x0",
    },
    {
        "nombre": "led projector shop 4k 3d all projector wifi mcast usb android models",
        "precio": "₹ 3,599",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/zemcfyu0xqve1-IN/image;s=272x0",
    },
    {
        "nombre": "We have new latest collection 5g watch online order book",
        "precio": "₹ 2,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/157cue0lbgy41-IN/image;s=272x0",
    },
    {
        "nombre": "BRAND NEW | FREE COD",
        "precio": "₹ 199",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/4jd7t652sw732-IN/image;s=272x0",
    },
    {
        "nombre": "BRAND NEW | FREE COD |",
        "precio": "₹ 299",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/2ik61wgeibgs-IN/image;s=272x0",
    },
    {
        "nombre": "Othakalmandapam Coconut trees,Farm land,10,20,25...cent available",
        "precio": "₹ 2,49,000",
        "descripcion": "Sin información",
        "localizacion": "OTHAKALMANDAPAM, COIMBATORE",
        "imagen": "https://apollo.olx.in/v1/files/ipvoyjwenlrf2-IN/image;s=272x0",
    },
    {
        "nombre": "Unnao j.j hospital ke pass jaipuriya school ke samne plot uplabdh hai",
        "precio": "₹ 12,60,000",
        "descripcion": "Sin información",
        "localizacion": "BADA CHOURAHA, UNNAO",
        "imagen": "https://apollo.olx.in/v1/files/pnvkzypdbmjl2-IN/image;s=272x0",
    },
    {
        "nombre": "iPhone 14 get refurbished at genuine price in your budget",
        "precio": "₹ 19,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/weq5vz4whfn21-IN/image;s=272x0",
    },
    {
        "nombre": "IPHONE 12 Pro (256GB VARIENT URGENT SELLING",
        "precio": "₹ 18,500",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/nksanimzs545-IN/image;s=272x0",
    },
    {
        "nombre": "Hyundai Xcent 2019 Petrol 64000 Km Driven",
        "precio": "₹ 5,99,900",
        "descripcion": "2019 - 64,000 km",
        "localizacion": "JAIN MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/n14ajao44p9c2-IN/image;s=272x0",
    },
    {
        "nombre": "Chevrolet Tavera 2011 Diesel Well Maintained",
        "precio": "₹ 2,50,000",
        "descripcion": "2011 - 100,000 km",
        "localizacion": "INDIRA GANDHI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/rac366h6gb7p3-IN/image;s=272x0",
    },
    {
        "nombre": "At Mhasala",
        "precio": "₹ 11,00,000",
        "descripcion": "Sin información",
        "localizacion": "SHASTRI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/0n0bxpnfaphk2-IN/image;s=272x0",
    },
    {
        "nombre": "Fossil watch",
        "precio": "₹ 2,000",
        "descripcion": "Sin información",
        "localizacion": "JAIN MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/ozfudzo7l9je1-IN/image;s=272x0",
    },
    {
        "nombre": "Plot for sale",
        "precio": "₹ 7,00,000",
        "descripcion": "Sin información",
        "localizacion": "SHAHANGADI, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/8bejot9vm0zq3-IN/image;s=272x0",
    },
    {
        "nombre": "Football studs",
        "precio": "₹ 950",
        "descripcion": "Sin información",
        "localizacion": "INDIRA GANDHI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/2lex0x77dlxa-IN/image;s=272x0",
    },
    {
        "nombre": "Pitambar Tipale",
        "precio": "₹ 15,000",
        "descripcion": "1 Bds - 1 Ba - 400 ft2",
        "localizacion": "DATTA MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/feew6cyj6r212-IN/image;s=272x0",
    },
    {
        "nombre": "Naira cut new dress with dupata",
        "precio": "₹ 800",
        "descripcion": "Sin información",
        "localizacion": "JAI BHIM CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/jh150ud3j2hn-IN/image;s=272x0",
    },
    {
        "nombre": "8K Omex Xnano Android 9.0 Dolby Audio 2.4G/5G WiFi BT 5.0 Projector",
        "precio": "₹ 15,600",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/f0466td97aoe2-IN/image;s=272x0",
    },
    {
        "nombre": "Bridal lehenga",
        "precio": "₹ 15,000",
        "descripcion": "Sin información",
        "localizacion": "KUKDE LAYOUT, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/pucgzqr5def62-IN/image;s=272x0",
    },
    {
        "nombre": "4K Decoding Projector Android 9.0 WiFi 5G BT Inbuilt Netflix Prime",
        "precio": "₹ 9,990",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/43lkdufruggn3-IN/image;s=272x0",
    },
    {
        "nombre": "T800 Ultra Smart Watch",
        "precio": "₹ 400",
        "descripcion": "Sin información",
        "localizacion": "ANANT NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/8iuqnmxniudr1-IN/image;s=272x0",
    },
    {
        "nombre": "NEW PHARMACY COUNTER - PHARMACY RACK - FULL MEDICAP FUENITURE",
        "precio": "₹ 85,000",
        "descripcion": "Sin información",
        "localizacion": "INDIRA GANDHI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/48db1h9a0urp-IN/image;s=272x0",
    },
    {
        "nombre": "Baggy fit shirt men",
        "precio": "₹ 599",
        "descripcion": "Sin información",
        "localizacion": "CHOTI GUJRI, YAVATMAL",
        "imagen": "https://apollo.olx.in/v1/files/i0jd0l47ivw42-IN/image;s=272x0",
    },
    {
        "nombre": "Sofa in the best condition only 3 yrs used",
        "precio": "₹ 10,500",
        "descripcion": "Sin información",
        "localizacion": "SHAHANGADI, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/a8x4x6tsrp3k1-IN/image;s=272x0",
    },
    {
        "nombre": "Vine colour beautiful lengha choli",
        "precio": "₹ 4,500",
        "descripcion": "Sin información",
        "localizacion": "JARIPATKA, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/9le3bkf35ulm1-IN/image;s=272x0",
    },
    {
        "nombre": "Hyundai Creta 1.6 SX Automatic Diesel, 2019, Diesel",
        "precio": "₹ 11,65,000",
        "descripcion": "2019 - 115,818 km",
        "localizacion": "KANDIVALI EAST, MUMBAI",
        "imagen": "https://apollo.olx.in/v1/files/kzc4mpnwbf203-IN/image;s=272x0",
    },
    {
        "nombre": "Hyundai Grand i10 1.2 CRDi Sportz, 2017, Diesel",
        "precio": "₹ 5,45,000",
        "descripcion": "2017 - 118,804 km",
        "localizacion": "MADHAPUR, HYDERABAD",
        "imagen": "https://apollo.olx.in/v1/files/5fbmc4eqgafi3-IN/image;s=272x0",
    },
    {
        "nombre": "i Phone 11",
        "precio": "₹ 6,500",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/e8vzcp1hayj83-IN/image;s=272x0",
    },
    {
        "nombre": "Iphone 15 256gb at low cost available",
        "precio": "₹ 25,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/kkll0yiudx8l2-IN/image;s=272x0",
    },
    {
        "nombre": "Maruti Suzuki Swift 2012 Diesel 170000 Km Driven",
        "precio": "₹ 4,00,000",
        "descripcion": "2012 - 170,000 km",
        "localizacion": "ASHIRWAD AREA, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/4zyszq68n0rf-IN/image;s=272x0",
    },
    {
        "nombre": "All paper clear .validity 2029",
        "precio": "₹ 85,000",
        "descripcion": "Sin información",
        "localizacion": "SHASTRI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/af3aohoz205k-IN/image;s=272x0",
    },
    {
        "nombre": "Plot in Hinganghat",
        "precio": "₹ 8,00,000",
        "descripcion": "Sin información",
        "localizacion": "HINGANGHAT, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/5juzj3r8m9cr1-IN/image;s=272x0",
    },
    {
        "nombre": "Shirt T-shirt jeans",
        "precio": "₹ 200",
        "descripcion": "Sin información",
        "localizacion": "SAONER ROAD, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/4gx2cc6ronxg1-IN/image;s=272x0",
    },
    {
        "nombre": "2 BHK FLAT For Rent At Jaripatka Nagpur",
        "precio": "₹ 16,000",
        "descripcion": "2 Bds - 2 Ba - 1200 ft2",
        "localizacion": "JARIPATKA, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/ssk16p681og21-IN/image;s=272x0",
    },
    {
        "nombre": "Wedding clothes for groom / men",
        "precio": "₹ 15,000",
        "descripcion": "Sin información",
        "localizacion": "CWC COMPANY, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/bwlup9sogb54-IN/image;s=272x0",
    },
    {
        "nombre": "1 room kitchen with attached washroom for rent",
        "precio": "₹ 4,500",
        "descripcion": "1 Bds - 1 Ba - 450 ft2",
        "localizacion": "JATPURA WARD, CHANDRAPUR",
        "imagen": "https://apollo.olx.in/v1/files/ya3t0o2kky961-IN/image;s=272x0",
    },
    {
        "nombre": "Wedding sharara",
        "precio": "₹ 8,000",
        "descripcion": "Sin información",
        "localizacion": "THANA, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/ztc8lrh9wnkz2-IN/image;s=272x0",
    },
    {
        "nombre": "Great Gamers Wholesale Ps2,Ps3,Ps4,Xbox360 All Gaming console",
        "precio": "₹ 12,999",
        "descripcion": "Sin información",
        "localizacion": "JAIN MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/qagojl3cgqzx1-IN/image;s=272x0",
    },
    {
        "nombre": "Bandhni dress packing pack",
        "precio": "₹ 350",
        "descripcion": "Sin información",
        "localizacion": "BHOSA, UMARSARA",
        "imagen": "https://apollo.olx.in/v1/files/ohikfiibwkya-IN/image;s=272x0",
    },
    {
        "nombre": "BoAt Rockerz 255 pro-black colour:Made in India",
        "precio": "₹ 500",
        "descripcion": "Sin información",
        "localizacion": "ADERSH NAGAR, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/2fw6w401sy11-IN/image;s=272x0",
    },
    {
        "nombre": "New Fancy bra",
        "precio": "₹ 299",
        "descripcion": "Sin información",
        "localizacion": "KHARABI, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/dl7kuw6p28ol-IN/image;s=272x0",
    },
    {
        "nombre": "New Jio Mifi dongle. OFFER AVAILABLE",
        "precio": "₹ 2,499",
        "descripcion": "Sin información",
        "localizacion": "MASTER COLONY, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/ssztd2pzbqf21-IN/image;s=272x0",
    },
    {
        "nombre": "Ledies kpdhe",
        "precio": "₹ 700",
        "descripcion": "Sin información",
        "localizacion": "GULSHAN NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/jhdf90rfum87-IN/image;s=272x0",
    },
    {
        "nombre": "WEDDING BEST HD NEW DRONE CAMERA WITH REMOT CONTROL..fez",
        "precio": "₹ 13,000",
        "descripcion": "Sin información",
        "localizacion": "BHAIMAREN, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/c5rboglqjgwv3-IN/image;s=272x0",
    },
    {
        "nombre": "Men's shoes",
        "precio": "₹ 450",
        "descripcion": "Sin información",
        "localizacion": "BAIHIRAM NAGAR, GHUGUS",
        "imagen": "https://apollo.olx.in/v1/files/ksce4zpc66yg2-IN/image;s=272x0",
    },
    {
        "nombre": "Whole sale offer RO, UV, UF, TDS , Water Purifer best deal shah",
        "precio": "₹ 2,750",
        "descripcion": "Sin información",
        "localizacion": "HARI NAGAR, DELHI",
        "imagen": "https://apollo.olx.in/v1/files/ftbzkrl70p2n3-IN/image;s=272x0",
    },
    {
        "nombre": "Building for Sale..can be used as Clinic for Doctors or Lodge",
        "precio": "₹ 2,60,00,000",
        "descripcion": "4+ Bds - 4+ Ba - 6000 ft2",
        "localizacion": "MANPRAI, MANAPPARAI",
        "imagen": "https://apollo.olx.in/v1/files/7jm3xx4ttkwx2-IN/image;s=272x0",
    },
    {
        "nombre": "Iphone 14 pro 256gb at low cost available",
        "precio": "₹ 31,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR MIDC, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/at5txmbtkypc2-IN/image;s=272x0",
    },
    {
        "nombre": "IPHONE 12PRO(256GB VARIENT URGENT SELLING",
        "precio": "₹ 18,400",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/zoapx4o5vucw1-IN/image;s=272x0",
    },
    {
        "nombre": "Maruti Suzuki Swift Dzire 2011",
        "precio": "₹ 2,70,000",
        "descripcion": "2011 - 142,000 km",
        "localizacion": "SANT TUKDOJI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/1s0t6t7tb0mf-IN/image;s=272x0",
    },
    {
        "nombre": "Maruti Suzuki Swift 2012 Diesel 120000 Km Driven",
        "precio": "₹ 3,30,000",
        "descripcion": "2012 - 120,000 km",
        "localizacion": "YESHWANT NAGAR, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/sixw34ufv0pr3-IN/image;s=272x0",
    },
    {
        "nombre": "Office space for Rent",
        "precio": "₹ 40,000",
        "descripcion": "Sin información",
        "localizacion": "PALAKWADI WARDHA, WARDHA",
        "imagen": "https://apollo.olx.in/v1/files/nvbgxb158gyr3-IN/image;s=272x0",
    },
    {
        "nombre": "Performax Shoes",
        "precio": "₹ 1,600",
        "descripcion": "Sin información",
        "localizacion": "SHYAM NAGAR COLONY, CHANDRAPUR",
        "imagen": "https://apollo.olx.in/v1/files/25tq3prmusai2-IN/image;s=272x0",
    },
    {
        "nombre": "Mauza: चिचाळा Plots for sale",
        "precio": "₹ 14,20,000",
        "descripcion": "Sin información",
        "localizacion": "GANDHI CHOWK, CHANDRAPUR",
        "imagen": "https://apollo.olx.in/v1/files/a5pafyvmnzso1-IN/image;s=272x0",
    },
    {
        "nombre": "REEBOK Training & Gym Shoes For Men (Size 6)",
        "precio": "₹ 1,800",
        "descripcion": "Sin información",
        "localizacion": "INDRA COLONY, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/yyjat8mzgvnj1-IN/image;s=272x0",
    },
    {
        "nombre": "PG for student and professional",
        "precio": "₹ 2,500",
        "descripcion": "1 Bds - 1 Ba - 150 ft2",
        "localizacion": "SANGAM THEATRE CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/md5pll7sjvgd1-IN/image;s=272x0",
    },
    {
        "nombre": "Boat watch just 2 months old for sell",
        "precio": "₹ 2,800",
        "descripcion": "Sin información",
        "localizacion": "KRISHNA NAGAR CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/1kny5i444ovk1-IN/image;s=272x0",
    },
    {
        "nombre": "Nikon D5600 Camera",
        "precio": "₹ 45,000",
        "descripcion": "Sin información",
        "localizacion": "MATA MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/g6hmqcc7d25a3-IN/image;s=272x0",
    },
    {
        "nombre": "PUMA T7 TURBO BLACK JACKET",
        "precio": "₹ 3,999",
        "descripcion": "Sin información",
        "localizacion": "NARENDRA NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/hua1uxty6x393-IN/image;s=272x0",
    },
    {
        "nombre": "Kitchen Rack",
        "precio": "₹ 1,200",
        "descripcion": "Sin información",
        "localizacion": "KOCHAR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/8z2ba818m9kf3-IN/image;s=272x0",
    },
    {
        "nombre": "Sadi dress",
        "precio": "₹ 900",
        "descripcion": "Sin información",
        "localizacion": "GOKULPETH, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/ge7yuvbhd5ta3-IN/image;s=272x0",
    },
    {
        "nombre": "Canon 1200 for sell",
        "precio": "₹ 20,000",
        "descripcion": "Sin información",
        "localizacion": "MATA MANDIR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/0bald4daz9gd2-IN/image;s=272x0",
    },
    {
        "nombre": "Smart watch 4g",
        "precio": "₹ 399",
        "descripcion": "Sin información",
        "localizacion": "ARYA NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/rr39nbhl1e78-IN/image;s=272x0",
    },
    {
        "nombre": "Queen Simple watch",
        "precio": "₹ 499",
        "descripcion": "Sin información",
        "localizacion": "MASTER COLONY, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/xj83z6ex4yjd1-IN/image;s=272x0",
    },
    {
        "nombre": "Original Coach Bag, brand new Diwali discount",
        "precio": "₹ 11,999",
        "descripcion": "Sin información",
        "localizacion": "NAGPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/xrv1magptglm2-IN/image;s=272x0",
    },
    {
        "nombre": "Hyundai i20 Diesel Sportz, 2016, Diesel",
        "precio": "₹ 6,40,000",
        "descripcion": "2016 - 83,184 km",
        "localizacion": "SANTHOSH NAGAR, HYDERABAD",
        "imagen": "https://apollo.olx.in/v1/files/bfitgqwq7egq-IN/image;s=272x0",
    },
    {
        "nombre": "Jeep Compass 1.4 Night Eagle Petrol AT, 2022, Petrol",
        "precio": "₹ 17,95,000",
        "descripcion": "2022 - 29,700 km",
        "localizacion": "GRANT ROAD AREA, MUMBAI",
        "imagen": "https://apollo.olx.in/v1/files/8gsrtu3qvjms1-IN/image;s=272x0",
    },
    {
        "nombre": "Selling my 6 months old Samsung s23ultra. Need urgent money",
        "precio": "₹ 30,000",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/tlr3dt8inylq2-IN/image;s=272x0",
    },
    {
        "nombre": "SELLING MY IPHONE 12 PRO MAX [ 5 MONTHS OLD ]",
        "precio": "₹ 20,500",
        "descripcion": "Sin información",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/0a3fepa5v83n2-IN/image;s=272x0",
    },
    {
        "nombre": "S-cross 2016 model button start good condition good mileage new tyre.",
        "precio": "₹ 5,60,000",
        "descripcion": "2016 - 90,000 km",
        "localizacion": "TILAK WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/v5div6zsagmq3-IN/image;s=272x0",
    },
    {
        "nombre": "Nagpur maharastra",
        "precio": "₹ 5,50,000",
        "descripcion": "2016 - 150,000 km",
        "localizacion": "SAMUDRAPUR, MAHARASHTRA",
        "imagen": "https://apollo.olx.in/v1/files/m1pmr4b4ppog1-IN/image;s=272x0",
    },
    {
        "nombre": "1room 1kitchen for rent",
        "precio": "₹ 5,000",
        "descripcion": "1 Bds - 1 Ba - 450 ft2",
        "localizacion": "MOTI BAGH, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/6fqy757ev6o12-IN/image;s=272x0",
    },
    {
        "nombre": "Tommy Hilfiger Premium Watch",
        "precio": "₹ 12,499",
        "descripcion": "Sin información",
        "localizacion": "CHHATRAPATI CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/rvqg4jnx8gu03-IN/image;s=272x0",
    },
    {
        "nombre": "1 room for rent",
        "precio": "₹ 3,500",
        "descripcion": "1 Bds - 1 Ba - 300 ft2",
        "localizacion": "PREM NAGAR JAY HIND SOCIETY, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/r9rukz1m18dl-IN/image;s=272x0",
    },
    {
        "nombre": "Original cotton set",
        "precio": "₹ 650",
        "descripcion": "Sin información",
        "localizacion": "NAIDU CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/21t88v7ta5ww1-IN/image;s=272x0",
    },
    {
        "nombre": "1bhk owner portion for rent",
        "precio": "₹ 6,000",
        "descripcion": "1 Bds - 2 Ba - 650 ft2",
        "localizacion": "PREM NAGAR JAY HIND SOCIETY, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/30woabya0phe3-IN/image;s=272x0",
    },
    {
        "nombre": "Oxidised Kalire Bangles",
        "precio": "₹ 155",
        "descripcion": "Sin información",
        "localizacion": "AZAMSHAHA CHOWK, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/bt3szcgm1l811-IN/image;s=272x0",
    },
    {
        "nombre": "lg colling refrigerator",
        "precio": "₹ 5,000",
        "descripcion": "Sin información",
        "localizacion": "YESHWANT NAGAR, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/h9v87bpdv35e1-IN/image;s=272x0",
    },
    {
        "nombre": "Heavy work Kurta for Men",
        "precio": "₹ 700",
        "descripcion": "Sin información",
        "localizacion": "CLERK TOWN, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/zu0oi0nnt7r42-IN/image;s=272x0",
    },
    {
        "nombre": "Crown amp 4002",
        "precio": "₹ 51,000",
        "descripcion": "Sin información",
        "localizacion": "SHASTRI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/v9316bu8l2i02-IN/image;s=272x0",
    },
    {
        "nombre": "Chairos Silver Mist Men Original Luxury Watch Brand New in low price",
        "precio": "₹ 42,000",
        "descripcion": "Sin información",
        "localizacion": "ITWARI, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/q28jjxuygdro-IN/image;s=272x0",
    },
    {
        "nombre": "Camera nikon",
        "precio": "₹ 15,000",
        "descripcion": "Sin información",
        "localizacion": "SHASTRI WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/j7hkun4lvk8o1-IN/image;s=272x0",
    },
    {
        "nombre": "Beautiful blazer",
        "precio": "₹ 1,001",
        "descripcion": "Sin información",
        "localizacion": "PRASAD NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/ddl860qh7l5o-IN/image;s=272x0",
    },
    {
        "nombre": "WEDDING BEST HD NEW DRONE CAMERA WITH REMOT CONTROL..SA",
        "precio": "₹ 13,000",
        "descripcion": "Sin información",
        "localizacion": "AHYANKAR WARD, HINGANGHAT",
        "imagen": "https://apollo.olx.in/v1/files/mlzfqzygbqdf2-IN/image;s=272x0",
    },
    {
        "nombre": "Tacsido suit blazer",
        "precio": "₹ 1,801",
        "descripcion": "Sin información",
        "localizacion": "PRASAD NAGAR, NAGPUR",
        "imagen": "https://apollo.olx.in/v1/files/2gsnvkkqkfq4-IN/image;s=272x0",
    },
]
